/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TehnicRouteImport } from './routes/tehnic'
import { Route as SistemRouteImport } from './routes/sistem'
import { Route as QbitRouteImport } from './routes/qbit'
import { Route as PlexRouteImport } from './routes/plex'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LansariRouteImport } from './routes/lansari'
import { Route as ImmichRouteImport } from './routes/immich'
import { Route as IndexRouteImport } from './routes/index'

const TehnicRoute = TehnicRouteImport.update({
  id: '/tehnic',
  path: '/tehnic',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemRoute = SistemRouteImport.update({
  id: '/sistem',
  path: '/sistem',
  getParentRoute: () => rootRouteImport,
} as any)
const QbitRoute = QbitRouteImport.update({
  id: '/qbit',
  path: '/qbit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlexRoute = PlexRouteImport.update({
  id: '/plex',
  path: '/plex',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LansariRoute = LansariRouteImport.update({
  id: '/lansari',
  path: '/lansari',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmichRoute = ImmichRouteImport.update({
  id: '/immich',
  path: '/immich',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/immich': typeof ImmichRoute
  '/lansari': typeof LansariRoute
  '/login': typeof LoginRoute
  '/plex': typeof PlexRoute
  '/qbit': typeof QbitRoute
  '/sistem': typeof SistemRoute
  '/tehnic': typeof TehnicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/immich': typeof ImmichRoute
  '/lansari': typeof LansariRoute
  '/login': typeof LoginRoute
  '/plex': typeof PlexRoute
  '/qbit': typeof QbitRoute
  '/sistem': typeof SistemRoute
  '/tehnic': typeof TehnicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/immich': typeof ImmichRoute
  '/lansari': typeof LansariRoute
  '/login': typeof LoginRoute
  '/plex': typeof PlexRoute
  '/qbit': typeof QbitRoute
  '/sistem': typeof SistemRoute
  '/tehnic': typeof TehnicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/immich'
    | '/lansari'
    | '/login'
    | '/plex'
    | '/qbit'
    | '/sistem'
    | '/tehnic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/immich'
    | '/lansari'
    | '/login'
    | '/plex'
    | '/qbit'
    | '/sistem'
    | '/tehnic'
  id:
    | '__root__'
    | '/'
    | '/immich'
    | '/lansari'
    | '/login'
    | '/plex'
    | '/qbit'
    | '/sistem'
    | '/tehnic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImmichRoute: typeof ImmichRoute
  LansariRoute: typeof LansariRoute
  LoginRoute: typeof LoginRoute
  PlexRoute: typeof PlexRoute
  QbitRoute: typeof QbitRoute
  SistemRoute: typeof SistemRoute
  TehnicRoute: typeof TehnicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tehnic': {
      id: '/tehnic'
      path: '/tehnic'
      fullPath: '/tehnic'
      preLoaderRoute: typeof TehnicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistem': {
      id: '/sistem'
      path: '/sistem'
      fullPath: '/sistem'
      preLoaderRoute: typeof SistemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qbit': {
      id: '/qbit'
      path: '/qbit'
      fullPath: '/qbit'
      preLoaderRoute: typeof QbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plex': {
      id: '/plex'
      path: '/plex'
      fullPath: '/plex'
      preLoaderRoute: typeof PlexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lansari': {
      id: '/lansari'
      path: '/lansari'
      fullPath: '/lansari'
      preLoaderRoute: typeof LansariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immich': {
      id: '/immich'
      path: '/immich'
      fullPath: '/immich'
      preLoaderRoute: typeof ImmichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImmichRoute: ImmichRoute,
  LansariRoute: LansariRoute,
  LoginRoute: LoginRoute,
  PlexRoute: PlexRoute,
  QbitRoute: QbitRoute,
  SistemRoute: SistemRoute,
  TehnicRoute: TehnicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
