/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TehnicRouteImport } from './routes/tehnic'
import { Route as SistemRouteImport } from './routes/sistem'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QbitRouteImport } from './routes/qbit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImmichRouteImport } from './routes/immich'
import { Route as DescoperaRouteImport } from './routes/descopera'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TehnicRoute = TehnicRouteImport.update({
  id: '/tehnic',
  path: '/tehnic',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemRoute = SistemRouteImport.update({
  id: '/sistem',
  path: '/sistem',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QbitRoute = QbitRouteImport.update({
  id: '/qbit',
  path: '/qbit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmichRoute = ImmichRouteImport.update({
  id: '/immich',
  path: '/immich',
  getParentRoute: () => rootRouteImport,
} as any)
const DescoperaRoute = DescoperaRouteImport.update({
  id: '/descopera',
  path: '/descopera',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/descopera': typeof DescoperaRoute
  '/immich': typeof ImmichRoute
  '/login': typeof LoginRoute
  '/qbit': typeof QbitRoute
  '/register': typeof RegisterRoute
  '/sistem': typeof SistemRoute
  '/tehnic': typeof TehnicRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/descopera': typeof DescoperaRoute
  '/immich': typeof ImmichRoute
  '/login': typeof LoginRoute
  '/qbit': typeof QbitRoute
  '/register': typeof RegisterRoute
  '/sistem': typeof SistemRoute
  '/tehnic': typeof TehnicRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/descopera': typeof DescoperaRoute
  '/immich': typeof ImmichRoute
  '/login': typeof LoginRoute
  '/qbit': typeof QbitRoute
  '/register': typeof RegisterRoute
  '/sistem': typeof SistemRoute
  '/tehnic': typeof TehnicRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/descopera'
    | '/immich'
    | '/login'
    | '/qbit'
    | '/register'
    | '/sistem'
    | '/tehnic'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/descopera'
    | '/immich'
    | '/login'
    | '/qbit'
    | '/register'
    | '/sistem'
    | '/tehnic'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/descopera'
    | '/immich'
    | '/login'
    | '/qbit'
    | '/register'
    | '/sistem'
    | '/tehnic'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  DescoperaRoute: typeof DescoperaRoute
  ImmichRoute: typeof ImmichRoute
  LoginRoute: typeof LoginRoute
  QbitRoute: typeof QbitRoute
  RegisterRoute: typeof RegisterRoute
  SistemRoute: typeof SistemRoute
  TehnicRoute: typeof TehnicRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tehnic': {
      id: '/tehnic'
      path: '/tehnic'
      fullPath: '/tehnic'
      preLoaderRoute: typeof TehnicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistem': {
      id: '/sistem'
      path: '/sistem'
      fullPath: '/sistem'
      preLoaderRoute: typeof SistemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qbit': {
      id: '/qbit'
      path: '/qbit'
      fullPath: '/qbit'
      preLoaderRoute: typeof QbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immich': {
      id: '/immich'
      path: '/immich'
      fullPath: '/immich'
      preLoaderRoute: typeof ImmichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descopera': {
      id: '/descopera'
      path: '/descopera'
      fullPath: '/descopera'
      preLoaderRoute: typeof DescoperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  DescoperaRoute: DescoperaRoute,
  ImmichRoute: ImmichRoute,
  LoginRoute: LoginRoute,
  QbitRoute: QbitRoute,
  RegisterRoute: RegisterRoute,
  SistemRoute: SistemRoute,
  TehnicRoute: TehnicRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
